### ISSUE TITLE
Fix description

### ISSUE THREAD

**Issue by ghost** [ghostlydilemma/powercord-manifest-generator#2]
On the themes tab, it displays:
![image](https://user-images.githubusercontent.com/48446328/69831450-c1a50d00-1229-11ea-9119-f1180486f6a1.png)
and
![image](https://user-images.githubusercontent.com/48446328/69831460-c8338480-1229-11ea-993d-171c67d6ff41.png)
They have the same description.
The theme one should be theme file name related.

**Comment by ghostlydilemma** [comment]
Fixed in 5c44fba
